SELECT USER_ID FROM weile.PUBLIC_USER_INFORMATION 
MINUS
SELECT USER_ID FROM VIEW_USER_INFORMATION;

SELECT * FROM VIEW_USER_INFORMATION
MINUS
SELECT * FROM weile.PUBLIC_USER_INFORMATION;


SELECT * FROM weile.PUBLIC_ARE_FRIENDS 
MINUS
SELECT * FROM VIEW_ARE_FRIENDS;

SELECT * FROM VIEW_ARE_FRIENDS
MINUS
SELECT * FROM weile.PUBLIC_ARE_FRIENDS;


SELECT * FROM weile.PUBLIC_PHOTO_INFORMATION 
MINUS
SELECT * FROM VIEW_PHOTO_INFORMATION;

SELECT * FROM VIEW_PHOTO_INFORMATION
MINUS
SELECT * FROM weile.PUBLIC_PHOTO_INFORMATION;


SELECT * FROM weile.PUBLIC_TAG_INFORMATION 
MINUS
SELECT * FROM VIEW_TAG_INFORMATION;

SELECT * FROM VIEW_TAG_INFORMATION
MINUS
SELECT * FROM weile.PUBLIC_TAG_INFORMATION;


SELECT * FROM weile.PUBLIC_EVENT_INFORMATION 
MINUS
SELECT * FROM VIEW_EVENT_INFORMATION;

SELECT * FROM VIEW_EVENT_INFORMATION
MINUS
SELECT * FROM weile.PUBLIC_EVENT_INFORMATION;