CREATE TABLE USER_INFORMATION AS (SELECT * FROM weile.PUBLIC_USER_INFORMATION);
CREATE TABLE ARE_FRIENDS AS (SELECT * FROM weile.PUBLIC_ARE_FRIENDS);
CREATE TABLE PHOTO_INFORMATION AS (SELECT * FROM weile.PUBLIC_PHOTO_INFORMATION;
CREATE TABLE TAG_INFORMATION AS (SELECT * FROM weile.PUBLIC_TAG_INFORMATION;
CREATE TABLE EVENT_INFORMATION AS (SELECT * FROM weile.PUBLIC_EVENT_INFORMATION);