
DROP TABLE FRIENDS;
DROP TABLE USER_CURRENT_CITY;
DROP TABLE USER_HOMETOWN_CITY;
DROP TABLE CITIES;
DROP TABLE MESSAGE;
DROP TABLE EDUCATION;
DROP TABLE PROGRAMS;
DROP TABLE PARTICIPANTS;
DROP TABLE USER_EVENTS;
DROP TABLE TAGS;
DROP TABLE PHOTOS;
DROP TABLE ALBUMS;
DROP TABLE USERS;